# Generated by Django 5.1.7 on 2025-05-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_bio_user_institute_user_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
