# Generated by Django 5.1.7 on 2025-05-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, default='Student', max_length=200, null=True),
        ),
    ]
