# Generated by Django 5.1.7 on 2025-03-24 05:24

import teachers.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
                ('objects', teachers.managers.CustomTeacherManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
    ]
