# Generated by Django 5.1.7 on 2025-03-25 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_studentsofteacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics_for_this_week', models.CharField(max_length=200)),
                ('topics', models.CharField(choices=[('Started', 'Started'), ('50% Completed', '25% Completed'), ('50% Completed', '50% Completed'), ('50% Completed', '50% Completed'), ('75% Completed', '75% Completed'), ('100% Completed', '100% Completed')], default='Started', max_length=15)),
                ('assignment', models.CharField(default='Coming Soon', max_length=150)),
                ('topics_completed', models.PositiveIntegerField(default=0)),
                ('student_progress', models.CharField(choices=[('Doing Well', 'Doing Well'), ('Need More Hardwork', 'Need More Hardwork'), ('Greate', 'Greate'), ('Not So Well', 'Not So Well')], default='Doing Well', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
