# Generated by Django 5.1.7 on 2025-03-27 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_alter_tuition_teacher_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='tuition',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='teachers.tuition'),
            preserve_default=False,
        ),
    ]
