# Generated by Django 5.1.7 on 2025-03-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_progress_tuition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='topics',
            field=models.CharField(choices=[('Started', 'Started'), ('25% Completed', '25% Completed'), ('50% Completed', '50% Completed'), ('75% Completed', '75% Completed'), ('100% Completed', '100% Completed')], default='Started', max_length=15),
        ),
    ]
